CC		= g++
CFLAGS		= -g -c -Wall -std=c++11
LDFLAGS		= -lpthread
SOURCES		= client.cpp tcpstream.cpp tcpconnector.cpp request.cpp
INCLUDES	= -I.
OBJECTS		= $(SOURCES:.cpp=.o)
TARGET		= client

all: $(SOURCES) $(TARGET)

$(TARGET): $(OBJECTS) 
	$(CC) $(OBJECTS) -o $@ $(LDFLAGS)

.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDES) $< $(LIBS) -o $@

clean:
	rm -rf *.o