CC		= g++
CFLAGS		= -g -c -Wall -std=c++11
LDFLAGS		= -lpthread
SOURCES		= server.cpp serverContainer.cpp tcpstream.cpp tcpacceptor.cpp request.cpp
INCLUDES	= -I.
OBJECTS		= $(SOURCES:.cpp=.o)
TARGET		= server

all: $(SOURCES) $(TARGET)

$(TARGET): $(OBJECTS) 
	$(CC) $(OBJECTS) -o $@ $(LDFLAGS)

.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDES) $< $(LIBS) -o $@

clean:
	rm *.o