CC		= g++
CFLAGS		= -g -c -Wall -std=c++11
LDFLAGS		= -lpthread
SOURCES		= server.cpp tcpstream.cpp tcpacceptor.cpp
INCLUDES	= -I.
OBJECTS		= $(SOURCES:.cpp=.o)
TARGET		= server

all: $(SOURCES) $(TARGET)

$(TARGET): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDES) $< $(LIBS) -o $@

clean:
	rm -rf $(OBJECTS) $(TARGET)